package Interfaz;

import Clases.Productos;
import Clases.Utils;
import Conectar.DaoProductos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class productoInterfaz extends javax.swing.JFrame {
        DaoProductos daoProductos = new DaoProductos();
        Productos producto = new Productos();
    public productoInterfaz() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
      
        producto.setNombre(txtNombre.getText());
        try {
            daoProductos.cargarTabla(tablaProducto);
            daoProductos.cargarTabla3(tablaProducto2);
            daoProductos.cTablaInvenProducto(tablaVisualizar);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(marcaInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Pane_Create = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnCrearProducto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        BtnRecargar1 = new javax.swing.JButton();
        BtnCerrarSesion1 = new javax.swing.JButton();
        txtStock1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnMenuCentral = new javax.swing.JButton();
        FondoMorado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Pane_Edit = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtStock2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnRecargar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProducto2 = new javax.swing.JTable();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        txtPrecio2 = new javax.swing.JTextField();
        imgflechafondo2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnCerrarSesion3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaVisualizar = new javax.swing.JTable();
        BtnCerrarSesion2 = new javax.swing.JButton();
        FondoMorado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pane_Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(81, 112, 215));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel10.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 20));

        txtNombre.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel10.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creación de Productos");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        BtnCrearProducto.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCrearProducto.setText("Crear");
        BtnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearProductoActionPerformed(evt);
            }
        });
        jPanel10.add(BtnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 110, -1));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaProducto);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 380, 350));

        BtnRecargar1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnRecargar1.setText("Recargar");
        BtnRecargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecargar1ActionPerformed(evt);
            }
        });
        jPanel10.add(BtnRecargar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        BtnCerrarSesion1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCerrarSesion1.setText("Cerrar sesión");
        BtnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesion1ActionPerformed(evt);
            }
        });
        jPanel10.add(BtnCerrarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 150, 30));

        txtStock1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel10.add(txtStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock:");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        BtnMenuCentral.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnMenuCentral.setText("Menu Central");
        BtnMenuCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuCentralActionPerformed(evt);
            }
        });
        jPanel10.add(BtnMenuCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 130, 30));

        FondoMorado.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        FondoMorado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha.png"))); // NOI18N
        jPanel10.add(FondoMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 490, 470));

        Pane_Create.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pane_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pane_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Crear", jPanel1);

        Pane_Edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(81, 112, 215));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtStock2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel7.add(txtStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, -1));

        txtNombre2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel7.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Editar de Producto");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        BtnRecargar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnRecargar.setText("Recargar");
        BtnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecargarActionPerformed(evt);
            }
        });
        jPanel7.add(BtnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, 30));

        tablaProducto2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Stock", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProducto2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProducto2);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 430, 330));

        BtnModificar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnModificarMouseClicked(evt);
            }
        });
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel7.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 30));

        BtnEliminar1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminar1ActionPerformed(evt);
            }
        });
        jPanel7.add(BtnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 110, 30));
        jPanel7.add(txtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 220, -1));

        imgflechafondo2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        imgflechafondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha.png"))); // NOI18N
        jPanel7.add(imgflechafondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 470));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        BtnCerrarSesion3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCerrarSesion3.setText("Cerrar sesión");
        BtnCerrarSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesion3ActionPerformed(evt);
            }
        });
        jPanel7.add(BtnCerrarSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 150, 30));

        Pane_Edit.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pane_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pane_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel11.setBackground(new java.awt.Color(81, 112, 215));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Visualizar productos");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        tablaVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaVisualizar);

        jPanel11.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 690, 350));

        BtnCerrarSesion2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BtnCerrarSesion2.setText("Cerrar sesión");
        BtnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesion2ActionPerformed(evt);
            }
        });
        jPanel11.add(BtnCerrarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        FondoMorado1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        FondoMorado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha.png"))); // NOI18N
        jPanel11.add(FondoMorado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 490, 470));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Visualizar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearProductoActionPerformed
        producto.setNombre(txtNombre.getText());

        try {
        // Conviritendo datos
        int stockInicial = Integer.parseInt(txtStock1.getText());
        // Enviando datos a la clase productos
        producto.setStock_inicial(stockInicial);
        // Conviritendo datos
        int precio = Integer.parseInt(txtPrecio.getText());
        // Enviando datos a la clase productos
        producto.setPrecio(precio);
        // LLamando metodos del DaoProdu
            daoProductos.crearProducto(producto);
            daoProductos.cargarTabla(tablaProducto);
            daoProductos.cargarTabla3(tablaProducto2);
            daoProductos.cTablaInvenProducto(tablaVisualizar);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(marcaInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.limpiarCampo1();
    }//GEN-LAST:event_BtnCrearProductoActionPerformed

    private void BtnRecargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecargar1ActionPerformed

    }//GEN-LAST:event_BtnRecargar1ActionPerformed

    private void BtnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesion1ActionPerformed
        Utils.AbrirLogin(this);
    }//GEN-LAST:event_BtnCerrarSesion1ActionPerformed

    private void tablaProducto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProducto2MouseClicked
        txtNombre2.setText(tablaProducto2.getValueAt(tablaProducto2.getSelectedRow(), 1).toString());
        txtStock2.setText(tablaProducto2.getValueAt(tablaProducto2.getSelectedRow(), 2).toString());
        txtPrecio2.setText(tablaProducto2.getValueAt(tablaProducto2.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tablaProducto2MouseClicked

    private void BtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseClicked
        if (tablaProducto2.getSelectedRow() != -1) {
            int id_producto = Integer.parseInt(tablaProducto2.getValueAt(tablaProducto2.getSelectedRow(), 0).toString());
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Desea modificar esta Producto?", "Modificación del Producto", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    producto.setId(id_producto);
                    producto.setNombre(txtNombre2.getText().trim());
                    producto.setPrecio(Integer.parseInt(txtPrecio2.getText()));
                    producto.setStock_inicial(Integer.parseInt(txtStock2.getText()));
                  
                    daoProductos.ModificarProducto(producto);
                    // Actualizar la tabla después de modificar el producto
                    daoProductos.cargarTabla3(tablaProducto2);
                    daoProductos.cTablaInvenProducto(tablaVisualizar);
                    JOptionPane.showMessageDialog(rootPane, "Producto modificada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar modificar la producto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un producto para modificar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnModificarMouseClicked

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminar1ActionPerformed
        int id_producto = 0;
        if (tablaProducto2.getSelectedRow() != -1) {
            id_producto = Integer.parseInt(tablaProducto2.getValueAt(tablaProducto2.getSelectedRow(), 0).toString());
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar producto?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    daoProductos.EliminarProducto(id_producto);
                    daoProductos.cargarTabla3(tablaProducto2);
                    daoProductos.cargarTabla(tablaProducto);
                    daoProductos.cTablaInvenProducto(tablaVisualizar);
                    this.limpiarCampo2();
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar eliminar el producto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una marca para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminar1ActionPerformed

    private void BtnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecargarActionPerformed
        try {
         daoProductos.cargarTabla3(tablaProducto2);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(marcaInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRecargarActionPerformed

    private void BtnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesion2ActionPerformed
        Utils.AbrirLogin(this);
    }//GEN-LAST:event_BtnCerrarSesion2ActionPerformed

    private void BtnMenuCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuCentralActionPerformed
        Utils.AbrirMenuCentral(this);
    }//GEN-LAST:event_BtnMenuCentralActionPerformed

    private void BtnCerrarSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productoInterfaz().setVisible(true);
            }
        });
    }
private void limpiarCampo1(){
txtNombre.setText("");
txtStock1.setText("");
txtPrecio.setText("");
} 

private void limpiarCampo2(){
    txtNombre2.setText("");
    txtStock2.setText("");
    txtPrecio2.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion1;
    private javax.swing.JButton BtnCerrarSesion2;
    private javax.swing.JButton BtnCerrarSesion3;
    private javax.swing.JButton BtnCrearProducto;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JButton BtnMenuCentral;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRecargar;
    private javax.swing.JButton BtnRecargar1;
    private javax.swing.JLabel FondoMorado;
    private javax.swing.JLabel FondoMorado1;
    private javax.swing.JPanel Pane_Create;
    private javax.swing.JPanel Pane_Edit;
    private javax.swing.JLabel imgflechafondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaProducto2;
    private javax.swing.JTable tablaVisualizar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtStock1;
    private javax.swing.JTextField txtStock2;
    // End of variables declaration//GEN-END:variables
}
