/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jonathan
 */
public class usuarioInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form usuarioDiseño4
     */
    public usuarioInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_insercion = new javax.swing.JTable();
        btn_delete_usu = new javax.swing.JButton();
        btn_edit_usu = new javax.swing.JButton();
        btn_update_usu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido_p = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboBox_marca_choose = new javax.swing.JComboBox<>();
        txt_nom_trab = new javax.swing.JTextField();
        txt_dv = new javax.swing.JTextField();
        txt_user_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_create_usu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_apellido_m = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        txt_buscador_usu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_back_usu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 101, 39));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(222, 101, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_insercion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_insercion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        table_insercion.setForeground(new java.awt.Color(222, 114, 54));
        table_insercion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Rol", "Usuaio", "Nombre Trabajador", "Rut", "Apellidos", "Telefono", "Correo Electronico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_insercion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 162, 520, 350));

        btn_delete_usu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_delete_usu.setText("Eliminar");
        jPanel1.add(btn_delete_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 100, 40));

        btn_edit_usu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_edit_usu.setText("Editar");
        jPanel1.add(btn_edit_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 100, 40));

        btn_update_usu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_update_usu.setText("Actualizar");
        jPanel1.add(btn_update_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 100, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Apellido Paterno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("UserName:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Rol");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nombre del Trabajador");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        txt_apellido_p.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Rut + DV");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 110, -1));

        comboBox_marca_choose.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboBox_marca_choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un rol", "Administrador", "Trabajador" }));
        jPanel1.add(comboBox_marca_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, 30));

        txt_nom_trab.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_nom_trab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, -1));

        txt_dv.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_dv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dvActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 30, -1));

        txt_user_name.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 160, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Gestion de Ingreso de Usuarios");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, -1));

        btn_create_usu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_create_usu.setText("Guardar");
        jPanel1.add(btn_create_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Apellido Materno");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Correo Electronico");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        txt_apellido_m.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_apellido_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, -1));

        txt_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 160, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Telefono");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        txt_email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, -1));

        jLabel6.setText("-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 10, -1));

        txt_rut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 110, -1));
        jPanel1.add(txt_buscador_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 180, 30));

        jLabel7.setText("Buscador");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 30));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        btn_back_usu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_back_usu.setText("REGRESAR");
        btn_back_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_usuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dvActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_txt_dvActionPerformed

    private void btn_back_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_back_usuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarioInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_usu;
    private javax.swing.JButton btn_create_usu;
    private javax.swing.JButton btn_delete_usu;
    private javax.swing.JButton btn_edit_usu;
    private javax.swing.JButton btn_update_usu;
    private javax.swing.JComboBox<String> comboBox_marca_choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_insercion;
    private javax.swing.JTextField txt_apellido_m;
    private javax.swing.JTextField txt_apellido_p;
    private javax.swing.JTextField txt_buscador_usu;
    private javax.swing.JTextField txt_dv;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nom_trab;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
