package Interfaz;

import Clases.Productos;
import Conectar.DaoInventario;
import Clases.Utils;
import Conectar.DaoProductos;
import Conectar.DaoVenta;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VentaInterfaz extends javax.swing.JFrame {
    DaoInventario inventario = new DaoInventario();
    Productos producto = new Productos();
    DaoProductos daoProductos = new DaoProductos();
    DaoVenta daoVenta = new DaoVenta();


    public VentaInterfaz() {
        initComponents();
        cargarTablaVenta();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        fondoazuliptitulo1 = new javax.swing.JPanel();
        titulotienda1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TxtCantidadVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnMenuCentral = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fondoazuliptitulo2 = new javax.swing.JPanel();
        titulotienda2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVentaDetalle = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelNombre1 = new javax.swing.JLabel();
        BtnCerrarSesion1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BtnMenuCentral1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoazuliptitulo1.setBackground(new java.awt.Color(51, 102, 255));

        titulotienda1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulotienda1.setForeground(new java.awt.Color(255, 255, 255));
        titulotienda1.setText("Venta");

        javax.swing.GroupLayout fondoazuliptitulo1Layout = new javax.swing.GroupLayout(fondoazuliptitulo1);
        fondoazuliptitulo1.setLayout(fondoazuliptitulo1Layout);
        fondoazuliptitulo1Layout.setHorizontalGroup(
            fondoazuliptitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoazuliptitulo1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(titulotienda1)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        fondoazuliptitulo1Layout.setVerticalGroup(
            fondoazuliptitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoazuliptitulo1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulotienda1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(fondoazuliptitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 70));

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NombreProducto", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVenta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 470, 340));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad vendida:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        TxtCantidadVenta.setText("0");
        jPanel1.add(TxtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 150, 30));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLabel5.setText("Producto seleccionado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        BtnGuardar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 30));

        LabelNombre.setText("Nombre");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        BtnCerrarSesion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnCerrarSesion.setText("Cerrar sesión");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 450, 520));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Registro de venta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        BtnMenuCentral.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnMenuCentral.setText("Menu Central");
        BtnMenuCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuCentralActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMenuCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 130, 30));

        jTabbedPane1.addTab("Venta", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoazuliptitulo2.setBackground(new java.awt.Color(51, 102, 255));

        titulotienda2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulotienda2.setForeground(new java.awt.Color(255, 255, 255));
        titulotienda2.setText("Venta");

        javax.swing.GroupLayout fondoazuliptitulo2Layout = new javax.swing.GroupLayout(fondoazuliptitulo2);
        fondoazuliptitulo2.setLayout(fondoazuliptitulo2Layout);
        fondoazuliptitulo2Layout.setHorizontalGroup(
            fondoazuliptitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoazuliptitulo2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(titulotienda2)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        fondoazuliptitulo2Layout.setVerticalGroup(
            fondoazuliptitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoazuliptitulo2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulotienda2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(fondoazuliptitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 70));

        tablaVentaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NombreProducto", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaVentaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentaDetalleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaVentaDetalle);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 470, 340));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad vendida:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        jLabel8.setText("Producto seleccionado:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        LabelNombre1.setText("Nombre");
        jPanel3.add(LabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        BtnCerrarSesion1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnCerrarSesion1.setText("Cerrar sesión");
        BtnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesion1ActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCerrarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("Detalle de venta");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        BtnMenuCentral1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnMenuCentral1.setText("Menu Central");
        BtnMenuCentral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuCentral1ActionPerformed(evt);
            }
        });
        jPanel3.add(BtnMenuCentral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 130, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 450, 520));

        jTabbedPane1.addTab("Detalles Venta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentaMouseClicked
      LabelNombre.setText(tablaVenta.getValueAt(tablaVenta.getSelectedRow(), 0).toString());   
    }//GEN-LAST:event_tablaVentaMouseClicked

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        realizarVenta();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        Utils.AbrirLogin(this);
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnMenuCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuCentralActionPerformed
        Utils.AbrirMenuCentral(this);
    }//GEN-LAST:event_BtnMenuCentralActionPerformed

    private void tablaVentaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentaDetalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVentaDetalleMouseClicked

    private void BtnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesion1ActionPerformed
        Utils.AbrirLogin(this);
    }//GEN-LAST:event_BtnCerrarSesion1ActionPerformed

    private void BtnMenuCentral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuCentral1ActionPerformed
        Utils.AbrirMenuCentral(this);
    }//GEN-LAST:event_BtnMenuCentral1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaInterfaz().setVisible(true);
            }
        });
    }
    // Metodos
private void realizarVenta() {
    int selectedRow = tablaVenta.getSelectedRow();
    
    if (selectedRow >= 0) {
        try {
            // variables para obtener los campos
            String nombreProducto = LabelNombre.getText();
            int cantidadVendida = Integer.parseInt(TxtCantidadVenta.getText());

            // Obtener el stock actual del producto seleccionado
            int stockActual = Integer.parseInt(tablaVenta.getValueAt(selectedRow, 1).toString());

            // Calcular el nuevo stock
            int nuevoStock = stockActual - cantidadVendida;
            if (nuevoStock < 0) {
                JOptionPane.showMessageDialog(this, "Cantidad vendida no puede ser mayor al stock actual.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // datos de pérdida no hay
            int cantidadPerdida = 0;
            String descripcionPerdida = "";

            // Actualizar el stock del producto en la base de datos
            daoProductos.actualizarStockProducto(nombreProducto, nuevoStock);

            // Insertar registro en la tabla de historial
            producto.setNombre(nombreProducto);
            producto.setStock_inicial(stockActual);
            inventario.insertarHistorial(producto, cantidadVendida, cantidadPerdida, descripcionPerdida, nuevoStock);

            // Recargar la tabla para mostrar el nuevo stock
            cargarTablaVenta();
            JOptionPane.showMessageDialog(this, "Venta registrada con éxito");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para la cantidad vendida.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VentaInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}


private void cargarTablaVenta() {
    try {
        daoProductos.cargarTabla2(tablaVenta);
        daoVenta.cargarTabla(tablaVentaDetalle);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(VentaInterfaz.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnCerrarSesion1;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnMenuCentral;
    private javax.swing.JButton BtnMenuCentral1;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JTextField TxtCantidadVenta;
    private javax.swing.JPanel fondoazuliptitulo1;
    private javax.swing.JPanel fondoazuliptitulo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTable tablaVentaDetalle;
    private javax.swing.JLabel titulotienda1;
    private javax.swing.JLabel titulotienda2;
    // End of variables declaration//GEN-END:variables
}
